### PR TITLE
1.1.0.1

### PR DESCRIPTION
**Pull request by seitenca**
@Dream-Master @richardhendricks any ideas to add to the mod?
(I implemented all things I want so quickly that now I'm out of ideas)

### CODE REVIEW

**Comment by Dream-Master** [comment]
@seitenca Feel free to add more stuff

**Comment by Dream-Master** [comment]
Maybe for the defence add-on mod

**Comment by Dream-Master** [comment]
@seitenca where are the Mine and Blade Battlegear solt are gone. ?
image

**Comment by Dream-Master** [comment]
there are 3 on the right side and 3 on the left side

**Comment by Dream-Master** [comment]
never mind if i take weapons there are there all fine :)
image

**Comment by seitenca** [comment]
Yes now the slots are shown when you are in the dual wielding mode, you can change it in the config file to show always

**Comment by Dream-Master** [comment]
@seitenca after switch back i cant use left click anymore?

**Comment by Dream-Master** [comment]
cant harvest things

**Comment by Dream-Master** [comment]
My bad nevermind was an issue on my side. Sorry

**Comment by seitenca** [comment]
Have you tested it with 1.0.8.5 version?

**Comment by seitenca** [comment]
@Dream-Master if you want to see what I have changed, see these photos https://www.curseforge.com/minecraft/mc-mods/battlegear2-unofficial/screenshots

**Comment by Dream-Master** [comment]
ok cool. Thanks for your work @seitenca . Are you on Discord ?

**Comment by seitenca** [comment]
@Dream-Master Yes, AIex#3425(i not L, because there are too many alex)

**Comment by Dream-Master** [comment]
@seitenca cant find you.
are you joined GTNH Discord ?

**Pull request merged**
